lib/regalocal_web/router.ex
defmodule RegalocalWeb.Router do
  use RegalocalWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RegalocalWeb.Plugs.Veil.Business
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RegalocalWeb do
    pipe_through :browser
    get "/business/:id", BusinessController, :show
    get "/coupons/:id/gifts/new", GiftController, :new
    post "/coupons/:id/gifts", GiftController, :create
    get "/gifts/:reference/payment_sent", GiftController, :payment_sent, as: :payment_sent

    resources("/faq", FaqController, only: [:index])
    get "/search", SearchController, :index
    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
    get "/cookies", PageController, :cookies
    get "/about", PageController, :about
  end

  # Other scopes may use custom stacks.
  # scope "/api", RegalocalWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/auth", RegalocalWeb.Veil do
    pipe_through(:browser)

    post("/businesses", BusinessController, :create, as: :veil_business)
    get("/businesses/new", BusinessController, :new, as: :veil_business)

    get("/sessions/new/:request_id", SessionController, :create)
    delete("/sessions/:session_id", SessionController, :delete)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate, RegalocalWeb.Plugs.Acceptance])

    get("/", DashboardController, :show)
    get("/orders", OrderController, :index)
    get("/orders/search", OrderController, :search)
    get("/orders/:id", OrderController, :show)
    put("/orders/:id/payment_received", OrderController, :payment_received, as: :payment_received)
    put("/orders/:id/redeem", OrderController, :redeem, as: :order_redeemed)
    get("/business", BusinessController, :show)
    resources("/coupons", CouponController)
    put("/coupons/:id/publish", CouponController, :publish, as: :publish_coupon)
    put("/coupons/:id/unpublish", CouponController, :unpublish, as: :unpublish_coupon)
    put("/coupons/:id/archive", CouponController, :archive, as: :archive_coupon)
    put("/coupons/:id/activate", CouponController, :activate, as: :activate_coupon)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate])

    get("/business/edit", BusinessController, :edit)
    put("/business", BusinessController, :update)
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox"
    end
  end
end

lib/regalocal_web/views/layout_view.ex
defmodule RegalocalWeb.LayoutView do
  use RegalocalWeb, :view

  def title(assigns) do
    title = forward_to_view(:title, assigns)
    if title, do: "#{title} - RegaLocal", else: "RegaLocal"
  end

  def meta_description(assigns) do
    forward_to_view(:meta_description, assigns) ||
      gettext("Ajuda als comerços i petits negocis a fer front a la crisi causada pel 🦠 COVID-19 i al mateix temps regala solidaritat als qui t'estimes.")
  end

  def logo(conn) do
    render("logo.html", %{conn: conn})
  end

  def menu_items(conn) do
    [
      %{title: gettext("Sobre nosaltres"), path: Routes.page_path(conn, :about)},
      %{title: gettext("Preguntes Freqüents"), path: Routes.faq_path(conn, :index)}
    ]
  end

  defp forward_to_view(name, assigns) do
    try do
      apply(assigns[:view_module], name, [Phoenix.Controller.action_name(assigns[:conn]), assigns])
    rescue
      UndefinedFunctionError -> nil
      FunctionClauseError -> nil
    end
  end
end

lib/regalocal_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title(assigns) %></title>
    <meta name="description" content="<%= meta_description(assigns) %>"/>
    <meta property="og:image" content="<%= Routes.static_url(@conn, "/images/social.png") %>" />
    <meta property="og:title" content="<%= title(assigns) %>" />
    <meta property="og:description" content="<%= meta_description(assigns) %>" />
    <meta name="twitter:card" content="summary"></meta>
  <meta name="theme-color" content="#d61f69" />
  <link rel="icon" type="image/png" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <script type="text/javascript">
    window.$crisp=[];window.CRISP_WEBSITE_ID="4c5c0f55-3698-46e2-8e30-5fac344bfe95";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();
  </script>
  <%= if @conn.assigns[:current_business] != nil do %>
    <script>
      $crisp.push(["set", "user:email", "<%= @conn.assigns[:current_business].email %>"]);
    </script>
  <% end %>
  <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <%= csrf_meta_tag() %>
</head>
<body>
  <main role="main" class="bg-texture">
    <%= render "header.html", assigns %>
    <%= if flash = get_flash(@conn, :info) do %>
      <div class="rounded-md bg-green-50 p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"/>
            </svg>
          </div>
          <div class="ml-3">
            <p class="text-sm leading-5 font-medium text-green-800">
              <%= flash %>
            </p>
          </div>
          <div class="ml-auto pl-3">
            <div class="-mx-1.5 -my-1.5">
              <button class="inline-flex rounded-md p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:bg-green-100 transition ease-in-out duration-150">
                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"/>
                </svg>
              </button>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= if error_flash = get_flash(@conn, :error) do %>
      <div class="rounded-md bg-red-50 p-4">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-red-400" fill="currentColor" viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"/>
            </svg>
          </div>
          <div class="ml-3">
            <p class="text-sm leading-5 font-medium text-green-800">
              <%= error_flash %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
    <%= render @view_module, @view_template, assigns %>
  </main>
  <footer role="footer">
    <%= render RegalocalWeb.LayoutView, "footer.html", assigns %>
  </footer>
  <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>

lib/regalocal_web/templates/layout/email.html.eex
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  </head>
  <style>
    /* -------------------------------------
        GLOBAL
    ------------------------------------- */
    * {
      margin: 0;
      padding: 0;
      font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
      box-sizing: border-box;
      font-size: 18px;
    }
    
    img {
      max-width: 100%;
    }
    
    body {
      -webkit-font-smoothing: antialiased;
      -webkit-text-size-adjust: none;
      width: 100% !important;
      height: 100%;
      line-height: 1.6;
    }
    
    /* Let's make sure all tables have defaults */
    table td {
      vertical-align: top;
    }
    
    /* -------------------------------------
        BODY & CONTAINER
    ------------------------------------- */
    body {
      background-color: #f6f6f6;
    }
    
    .body-wrap {
      background-color: #f6f6f6;
      width: 100%;
    }
    
    .container {
      display: block !important;
      max-width: 600px !important;
      margin: 0 auto !important;
      /* makes it centered */
      clear: both !important;
    }
    
    .content {
      max-width: 600px;
      margin: 0 auto;
      display: block;
      padding: 20px;
    }
    
    /* -------------------------------------
        HEADER, FOOTER, MAIN
    ------------------------------------- */
    .main {
      background: #fff;
      border: 1px solid #e9e9e9;
      border-radius: 3px;
    }
    
    .content-wrap {
      padding: 20px;
    }
    
    .content-block {
      padding: 0 0 20px;
    }
    
    .header {
      width: 100%;
      margin-bottom: 20px;
    }
    
    .header-content {
      padding: 0 40px;
    }
    
    .footer {
      width: 100%;
      clear: both;
      color: #999;
      padding: 20px;
    }
    .footer a {
      color: #999;
    }
    .footer p, .footer a, .footer unsubscribe, .footer td {
      font-size: 12px;
    }
    
    .header {
      margin: 40px 0 0;
    }
    
    .header h1, .header h2 {
      margin: 0;
      font-weight: bold;
    }
    
    .header h1 {
      color: #e74694;
    }
    
    /* -------------------------------------
        GRID AND COLUMNS
    ------------------------------------- */
    .column-left {
      float: left;
      width: 50%;
    }
    
    .column-right {
      float: left;
      width: 50%;
    }
    
    /* -------------------------------------
        TYPOGRAPHY
    ------------------------------------- */
    h1, h2, h3 {
      font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
      color: #000;
      margin: 40px 0 0;
      line-height: 1.2;
      font-weight: 400;
    }
    
    h1 {
      font-size: 32px;
      font-weight: 500;
    }
    
    h2 {
      font-size: 24px;
    }
    
    h3 {
      font-size: 18px;
    }
    
    h4 {
      font-size: 14px;
      font-weight: 600;
    }
    
    p, ul, ol {
      margin-bottom: 20px;
      font-weight: normal;
    }
    p li, ul li, ol li {
      margin-left: 5px;
      list-style-position: inside;
    }
    
    /* -------------------------------------
        LINKS & BUTTONS
    ------------------------------------- */
    a {
      color: #e74694;
      text-decoration: underline;
    }
    
    .actions {
      margin: 20px 0;
      text-align: center;
    }
    
    .btn-primary {
      text-decoration: none;
      color: #FFF;
      background-color: #e74694;
      border: solid #e74694;
      border-width: 10px 20px;
      line-height: 2;
      font-weight: bold;
      text-align: center;
      cursor: pointer;
      display: inline-block;
      border-radius: 5px;
      text-transform: capitalize;
    }
    
    /* -------------------------------------
        OTHER STYLES THAT MIGHT BE USEFUL
    ------------------------------------- */
    .last {
      margin-bottom: 0;
    }
    
    .first {
      margin-top: 0;
    }
    
    .padding {
      padding: 10px 0;
    }
    
    .aligncenter {
      text-align: center;
    }
    
    .alignright {
      text-align: right;
    }
    
    .alignleft {
      text-align: left;
    }
    
    .clear {
      clear: both;
    }
    
    /* -------------------------------------
        Alerts
    ------------------------------------- */
    .alert {
      font-size: 16px;
      color: #fff;
      font-weight: 500;
      padding: 20px;
      text-align: center;
      border-radius: 3px 3px 0 0;
    }
    .alert a {
      color: #fff;
      text-decoration: none;
      font-weight: 500;
      font-size: 16px;
    }
    .alert.alert-warning {
      background: #ff9f00;
    }
    .alert.alert-bad {
      background: #d0021b;
    }
    .alert.alert-good {
      background: #68b90f;
    }
    
    /* -------------------------------------
        INVOICE
    ------------------------------------- */
    .invoice {
      margin: 40px auto;
      text-align: left;
      width: 80%;
    }
    .invoice td {
      padding: 5px 0;
    }
    .invoice .invoice-items {
      width: 100%;
    }
    .invoice .invoice-items td {
      border-top: #eee 1px solid;
    }
    .invoice .invoice-items .total td {
      border-top: 2px solid #333;
      border-bottom: 2px solid #333;
      font-weight: 700;
    }
    
    /* -------------------------------------
        RESPONSIVE AND MOBILE FRIENDLY STYLES
    ------------------------------------- */
    @media only screen and (max-width: 640px) {
      h1, h2, h3, h4 {
        font-weight: 600 !important;
        margin: 20px 0 5px !important;
      }
    
      h1 {
        font-size: 22px !important;
      }
    
      h2 {
        font-size: 18px !important;
      }
    
      h3 {
        font-size: 16px !important;
      }
    
      .container {
        width: 100% !important;
      }
    
      .content, .content-wrapper {
        padding: 10px !important;
      }
    
      .invoice {
        width: 100% !important;
      }
    }
    
    /* -------------------------------------
        REGALOCAL STYLES
    ------------------------------------- */
    
    .message {
      padding: 10px;
      border: 1px dashed #e9e9e9;
      background-color: #f7f7f7;
      margin-bottom: 20px;
    }
    
    .gift {
      border: 1px dashed #fad1e8;
      text-align: center;
      color: #e74694;
      padding: 20px 10px;
      background: #fffcfe;
    }
  </style>
  <body>
    <table class="body-wrap">
      <tr>
        <td></td>
        <td class="container" width="600">
          <div class="content">
            <%= render @view_module, @view_template, assigns %>
            <div class="footer">
              <table width="100%">
                <tr>
                  <td class="aligncenter content-block"><%= link gettext("Regalocal"), to: RegalocalWeb.Endpoint.url %></td>
                </tr>
              </table>
            </div>
          </div>
        </td>
        <td></td>
      </tr>
    </table>
  </body>
</html>

lib/regalocal_web/templates/layout/footer.html.eex
<div class="bg-white border-t border-primary-100">
  <div class="max-w-screen-xl mx-auto py-12 px-6 sm:px-8 lg:py-16 lg:px-8">
    <div class="lg:grid lg:grid-cols-2 lg:gap-8">
      <div class="xl:col-span-1 mb-8">
        <%= link(to: Routes.page_path(@conn, :index)) do %>
          <%= logo(@conn) %>
        <% end %>
        <p class="mt-8 text-gray-500 text-base leading-6 max-w-md">
          <%= gettext("Ajudem a la recuperació de l'economia local, sense oblidar-nos dels qui estimem.") %>
        </p>
        <div class="mt-8 flex">
          <a href="https://github.com/codegram/regalocal" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">GitHub</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd"/>
            </svg>
          </a>
        </div>
      </div>
      <div class="flex justify-between">
        <div class="flex-grow lg:flex-initial">
          <h4 class="text-sm leading-5 font-semibold tracking-wider text-gray-400 uppercase">
            <%= gettext("Informació") %>
          </h4>
          <ul class="mt-4">
            <li>
              <a href="/about" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                <%= gettext("Sobre nosaltres") %>
              </a>
            </li>
            <li class="mt-4">
              <a href="/privacy" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                <%= gettext("Privacitat") %>
              </a>
            </li>
            <li class="mt-4">
              <a href="/cookies" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                <%= gettext("Cookies") %>
              </a>
            </li>
            <li class="mt-4">
              <a href="/terms" class="text-base leading-6 text-gray-500 hover:text-gray-900">
                <%= gettext("Avís legal") %>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="mt-12 border-t border-gray-200 pt-8">
      <p class="text-base leading-6 text-gray-400 xl:text-center">
        &copy; 2020 <a href="https://codegram.com">Codegram Technologies S.L.</a>
      </p>
    </div>
  </div>
</div>

lib/regalocal_web/templates/layout/header.html.eex
<div class="relative">
  <div x-data="{ open: false }" class="relative pt-6 pb-6">
    <div class="max-w-screen-xl mx-auto px-6 sm:px-8">
      <nav class="relative flex items-center justify-between sm:h-10 md:justify-center">
        <div class="flex items-center flex-1 md:absolute md:inset-y-0 md:left-0">
          <div class="flex items-center justify-between w-full md:w-auto">
            <%= link(to: Routes.page_path(@conn, :index)) do %>
              <%= logo(@conn) %>
            <% end %>
            <div class="-mr-2 flex items-center md:hidden">
              <button @click="open = true" type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div class="hidden md:block">
          <%= for item <- menu_items(@conn) do %>
            <%= link to: item.path, class: "mx-5 #{if menu_item_active?(@conn, item), do: "text-gray-900"}" do %>
              <%= item.title %>
            <% end %>
          <% end %>
        </div>
        <div class="hidden md:absolute md:flex md:items-center md:justify-end md:inset-y-0 md:right-0">
          <%= if assigns[:current_business] do %>
            <%= link gettext("Accedir al panell"), to: Routes.admin_dashboard_path(@conn, :show), class: "button button-reverse" %>
          <% else %>
            <%= link gettext("Sóc un comerç"), to: Routes.veil_business_path(@conn, :new), class: "button button-reverse" %>
          <% end %>
        </div>
      </nav>
    </div>
    <div x-show="open" style="display: none;" class="absolute top-0 inset-x-0 p-2 md:hidden z-50">
      <div class="rounded-lg shadow-md transition transform origin-top-right" x-show="open" x-transition:enter="duration-150 ease-out" x-transition:enter-start="opacity-0 scale-95" x-transition:enter-end="opacity-100 scale-100" x-transition:leave="duration-100 ease-in" x-transition:leave-start="opacity-100 scale-100" x-transition:leave-end="opacity-0 scale-95">
        <div class="rounded-lg bg-white shadow-xs overflow-hidden">
          <div class="px-5 pt-4 flex items-center justify-between">
            <div>
              <%= link(to: Routes.page_path(@conn, :index)) do %>
                <%= logo(@conn) %>
              <% end %>
            </div>
            <div class="-mr-2">
              <button @click="open = false" type="button" class="p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
          <div class="px-2 pt-2 pb-3">
            <%= for item <- menu_items(@conn) do %>
              <%= link to: item.path, class: "block mb-1 px-3 py-2 rounded-md text-base font-medium text-gray-700 hover:text-gray-900 hover:bg-gray-50 focus:outline-none focus:text-gray-900 focus:bg-gray-50 transition duration-150 ease-in-out" do %>
                <%= item.title %>
              <% end %>
            <% end %>
          </div>
          <div>
            <%= if assigns[:current_business] do %>
              <%= link gettext("Accedir al panell"), to: Routes.admin_dashboard_path(@conn, :show), class: "block w-full px-5 py-3 text-center font-medium text-primary-600 bg-gray-50 hover:bg-gray-100 hover:text-primary-700 focus:outline-none focus:bg-gray-100 focus:text-primary-700 transition duration-150 ease-in-out" %>
            <% else %>
              <%= link gettext("Sóc un comerç"), to: Routes.veil_business_path(@conn, :new), class: "block w-full px-5 py-3 text-center font-medium text-primary-600 bg-gray-50 hover:bg-gray-100 hover:text-primary-700 focus:outline-none focus:bg-gray-100 focus:text-primary-700 transition duration-150 ease-in-out" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

lib/regalocal_web/templates/layout/logo.html.eex
<span class="logo">
  <span class="logo-r">R</span><span class="logo-l">L<span>
</span>