lib/regalocal_web/router.ex
defmodule RegalocalWeb.Router do
  use RegalocalWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RegalocalWeb.Plugs.Veil.Business
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RegalocalWeb do
    pipe_through :browser
    get "/business/:id", BusinessController, :show
    get "/coupons/:id/gifts/new", GiftController, :new
    post "/coupons/:id/gifts", GiftController, :create
    get "/gifts/:reference/payment_sent", GiftController, :payment_sent, as: :payment_sent

    resources("/faq", FaqController, only: [:index])
    get "/search", SearchController, :index
    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
    get "/cookies", PageController, :cookies
    get "/about", PageController, :about
  end

  # Other scopes may use custom stacks.
  # scope "/api", RegalocalWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/auth", RegalocalWeb.Veil do
    pipe_through(:browser)

    post("/businesses", BusinessController, :create, as: :veil_business)
    get("/businesses/new", BusinessController, :new, as: :veil_business)

    get("/sessions/new/:request_id", SessionController, :create)
    delete("/sessions/:session_id", SessionController, :delete)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate, RegalocalWeb.Plugs.Acceptance])

    get("/", DashboardController, :show)
    get("/orders", OrderController, :index)
    get("/orders/search", OrderController, :search)
    get("/orders/:id", OrderController, :show)
    put("/orders/:id/payment_received", OrderController, :payment_received, as: :payment_received)
    put("/orders/:id/redeem", OrderController, :redeem, as: :order_redeemed)
    get("/business", BusinessController, :show)
    resources("/coupons", CouponController)
    put("/coupons/:id/publish", CouponController, :publish, as: :publish_coupon)
    put("/coupons/:id/unpublish", CouponController, :unpublish, as: :unpublish_coupon)
    put("/coupons/:id/archive", CouponController, :archive, as: :archive_coupon)
    put("/coupons/:id/activate", CouponController, :activate, as: :activate_coupon)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate])

    get("/business/edit", BusinessController, :edit)
    put("/business", BusinessController, :update)
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox"
    end
  end
end

lib/regalocal/search.ex
defmodule Regalocal.Search do
  import Ecto.Query, warn: false
  import Geo.PostGIS

  alias Regalocal.Repo
  alias Regalocal.Admin.Business
  alias Regalocal.Admin.Coupon

  def find_businesses_near!(%Geo.Point{} = geom, limit) do
    bids = business_ids_with_coupons()

    Business
    |> select([b], %{b | distance_meters: st_distance_in_meters(b.coordinates, ^geom)})
    |> where([b], b.id in ^bids)
    |> where(accepted_terms: true)
    |> order_by([b], st_distance_in_meters(b.coordinates, ^geom))
    |> limit(^limit)
    |> Repo.all()
  end

  defp business_ids_with_coupons() do
    Coupon
    |> select([:business_id])
    |> where(
      [c],
      c.status in ["published", "redeemable"] and c.archived == false and
        not is_nil(c.business_id)
    )
    |> Repo.all()
    |> Enum.map(fn c -> c.business_id end)
    |> Enum.uniq()
  end

  def get_business!(id), do: Business |> where(id: ^id, accepted_terms: true) |> Repo.one!()

  def active_coupons_for(%Business{id: business_id}) do
    Coupon
    |> where(business_id: ^business_id)
    |> where([c], c.status in ["published", "redeemable"] and c.archived == false)
    |> Repo.all()
  end
end

lib/regalocal_web/controllers/search_controller.ex
defmodule RegalocalWeb.SearchController do
  use RegalocalWeb, :controller
  alias Regalocal.Search
  alias Regalocal.Geolocation

  @spec index(Plug.Conn.t(), map) :: Plug.Conn.t()
  def index(conn, %{"latitude" => latitude, "longitude" => longitude}) do
    geo =
      Geolocation.to_geopoint(%{lat: String.to_float(latitude), lon: String.to_float(longitude)})

    businesses = Search.find_businesses_near!(geo, 25)

    conn
    |> assign(:businesses, businesses)
    |> render("index.html")
  end
end

lib/regalocal_web/views/search_view.ex
defmodule RegalocalWeb.SearchView do
  use RegalocalWeb, :view
  import RegalocalWeb.PublicLayoutHelpers
  alias RegalocalWeb.BusinessHelpers, as: Business

  def title(:index, _assigns) do
    gettext("Cercant comerços al teu voltant")
  end
end

lib/regalocal_web/templates/search/index.html.eex
<%= container do %>
  <div class="grid gap-5 mx-auto md:grid-cols-2 lg:grid-cols-3">
    <%= for business <- @businesses do %>
      <%= link to: Routes.business_path(@conn, :show, business), class: "flex relative flex-col rounded-lg shadow-md overflow-hidden border border-gray-100 hover:shadow-lg hover:border-gray-200 focus:shadow-md focus:bg-primary-50 focus:border-primary-300" do %>
        <div class="flex-1 p-6 flex flex-col justify-between">
          <div class="flex-1">
            <p class="text-sm leading-5 font-medium text-primary-600">
              a <%= Float.round(business.distance_meters / 1000, 2) %> Km
            </p>
            <h3 class="mt-2 text-xl leading-7 font-semibold text-gray-900">
              <%= business.name %>
            </h3>
            <p class="mt-3 text-base leading-6 text-gray-500">
              <%= String.slice(business.story, 0..180) %>...
            </p>
          </div>
          <div class="mt-6 flex items-center">
            <div class="flex-shrink-0">
              <%= Business.picture(business, 10) %>
            </div>
            <div class="ml-3">
              <p class="text-sm leading-5 font-medium text-gray-900">
                <%= business.owner_name %>
              </p>
              <div class="flex text-sm leading-5 text-gray-500">
                <%= if business.website do %>
                  <%= business.website %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>