lib/regalocal_web/router.ex
defmodule RegalocalWeb.Router do
  use RegalocalWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RegalocalWeb.Plugs.Veil.Business
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RegalocalWeb do
    pipe_through :browser
    get "/business/:id", BusinessController, :show
    get "/coupons/:id/gifts/new", GiftController, :new
    post "/coupons/:id/gifts", GiftController, :create
    get "/gifts/:reference/payment_sent", GiftController, :payment_sent, as: :payment_sent

    resources("/faq", FaqController, only: [:index])
    get "/search", SearchController, :index
    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
    get "/cookies", PageController, :cookies
    get "/about", PageController, :about
  end

  # Other scopes may use custom stacks.
  # scope "/api", RegalocalWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/auth", RegalocalWeb.Veil do
    pipe_through(:browser)

    post("/businesses", BusinessController, :create, as: :veil_business)
    get("/businesses/new", BusinessController, :new, as: :veil_business)

    get("/sessions/new/:request_id", SessionController, :create)
    delete("/sessions/:session_id", SessionController, :delete)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate, RegalocalWeb.Plugs.Acceptance])

    get("/", DashboardController, :show)
    get("/orders", OrderController, :index)
    get("/orders/search", OrderController, :search)
    get("/orders/:id", OrderController, :show)
    put("/orders/:id/payment_received", OrderController, :payment_received, as: :payment_received)
    put("/orders/:id/redeem", OrderController, :redeem, as: :order_redeemed)
    get("/business", BusinessController, :show)
    resources("/coupons", CouponController)
    put("/coupons/:id/publish", CouponController, :publish, as: :publish_coupon)
    put("/coupons/:id/unpublish", CouponController, :unpublish, as: :unpublish_coupon)
    put("/coupons/:id/archive", CouponController, :archive, as: :archive_coupon)
    put("/coupons/:id/activate", CouponController, :activate, as: :activate_coupon)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate])

    get("/business/edit", BusinessController, :edit)
    put("/business", BusinessController, :update)
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox"
    end
  end
end

lib/regalocal_web/templates/admin_layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || gettext("Panell d'administració - Regalocal") %></title>
    <meta name="theme-color" content="#d61f69" />
    <link rel="icon" type="image/png" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">
    <script type="text/javascript">
      window.$crisp=[];window.CRISP_WEBSITE_ID="4c5c0f55-3698-46e2-8e30-5fac344bfe95";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();
    </script>
    <%= if @conn.assigns[:current_business] != nil do %>
      <script>
        $crisp.push(["set", "user:email", "<%= @conn.assigns[:current_business].email %>"]);
      </script>
    <% end %>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <div>
      <nav x-data="{ open: false }" @keydown.window.escape="open = false" class="bg-primary-700">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex items-center justify-between h-16">
            <div class="flex items-center">
              <div class="flex-shrink-0">
                <%= link(to: Routes.admin_dashboard_path(@conn, :show)) do %>
                  <%= logo(@conn) %>
                <% end %>
              </div>
              <div class="hidden md:block">
                <div class="ml-10 flex items-baseline">
                  <%= for item <- menu_items(@conn) do %>
                    <%= link to: item.path, class: "mr-4 px-3 py-2 rounded-md text-sm font-medium #{if menu_item_active?(@conn, item), do: "text-white bg-primary-800 focus:outline-none focus:text-white focus:bg-primary-600", else: "text-primary-200 hover:text-white hover:bg-primary-600 focus:outline-none focus:text-white focus:bg-primary-600"}" do %>
                      <%= item.title %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="hidden md:block">
              <div class="ml-4 flex items-end md:ml-6">
                <div @click.away="open = false" class="ml-3 relative" x-data="{ open: false }">
                  <div>
                    <button @click="open = !open" class="p-2 flex items-end text-sm rounded text-white focus:outline-none focus:shadow-solid" id="user-menu" aria-label="User menu" aria-haspopup="true" x-bind:aria-expanded="open">
                      <div class="mr-3 text-right">
                        <div class="text-base font-medium leading-none text-white"><%= Business.owner_name(current_business(@conn)) %></div>
                        <div class="mt-1 text-sm font-medium leading-none text-primary-300"><%= Business.email(current_business(@conn)) %></div>
                      </div>
                      <%= Business.picture(current_business(@conn), 8) %>
                    </button>
                  </div>
                  <div x-show="open" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95" class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg">
                    <div class="py-1 rounded-md bg-white shadow-xs">
                      <%= link gettext("Desconnectar"), to: Routes.session_path(@conn, :delete, @session_unique_id), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100", role: "menuitem", method: "delete" %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="-mr-2 flex md:hidden">
              <button @click="open = !open" class="inline-flex items-center justify-center p-2 rounded-md text-primary-300 hover:text-white hover:bg-primary-600 focus:outline-none focus:bg-primary-600 focus:text-white" x-bind:aria-label="open ? 'Close main menu' : 'Main menu'" x-bind:aria-expanded="open">
                <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                  <path :class="{'hidden': open, 'inline-flex': !open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                  <path :class="{'hidden': !open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div :class="{'block': open, 'hidden': !open}" class="hidden md:hidden">
          <div class="px-2 pt-2 pb-3 sm:px-3">
            <%= for item <- menu_items(@conn) do %>
              <%= link to: item.path, class: "mb-1 block px-3 py-2 rounded-md text-base font-medium #{if menu_item_active?(@conn, item), do: "text-white bg-primary-800 focus:outline-none focus:text-white focus:bg-gray-700", else: "text-primary-200 hover:text-white hover:bg-primary-600 focus:outline-none focus:text-white focus:bg-primary-600"}" do %>
                <%= item.title %>
              <% end %>
            <% end %>
          </div>
          <div class="pt-4 pb-3 border-t border-primary-800">
            <div class="flex items-center px-5">
              <div class="flex-shrink-0">
                <%= Business.picture(current_business(@conn), 8) %>
              </div>
              <div class="ml-3">
                <div class="text-base font-medium leading-none text-white"><%= Business.name(current_business(@conn)) %></div>
                <div class="mt-1 text-sm font-medium leading-none text-primary-300"><%= Business.email(current_business(@conn)) %></div>
              </div>
            </div>
            <div class="mt-3 px-2" role="menu" aria-orientation="vertical" aria-labelledby="user-menu" role="menuitem">
              <%= link gettext("Desconnectar"), to: Routes.session_path(@conn, :delete, @session_unique_id), class: "mt-1 block px-3 py-2 rounded-md text-base font-medium text-primary-300 hover:text-white hover:bg-primary-600 focus:outline-none focus:text-white focus:bg-primary-600", role: "menuitem", method: "delete" %>
            </div>
          </div>
        </div>
      </nav>
      <%= render @view_module, @view_template, assigns %>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/regalocal_web/templates/admin_layout/logo.html.eex
<span class="logo">
  <span class="logo-r text-white">R</span><span class="logo-l white">L<span>
    </span>