lib/regalocal_web/router.ex
defmodule RegalocalWeb.Router do
  use RegalocalWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RegalocalWeb.Plugs.Veil.Business
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RegalocalWeb do
    pipe_through :browser
    get "/business/:id", BusinessController, :show
    get "/coupons/:id/gifts/new", GiftController, :new
    post "/coupons/:id/gifts", GiftController, :create
    get "/gifts/:reference/payment_sent", GiftController, :payment_sent, as: :payment_sent

    resources("/faq", FaqController, only: [:index])
    get "/search", SearchController, :index
    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/privacy", PageController, :privacy
    get "/cookies", PageController, :cookies
    get "/about", PageController, :about
  end

  # Other scopes may use custom stacks.
  # scope "/api", RegalocalWeb do
  #   pipe_through :api
  # end

  # Default Routes for Veil
  scope "/auth", RegalocalWeb.Veil do
    pipe_through(:browser)

    post("/businesses", BusinessController, :create, as: :veil_business)
    get("/businesses/new", BusinessController, :new, as: :veil_business)

    get("/sessions/new/:request_id", SessionController, :create)
    delete("/sessions/:session_id", SessionController, :delete)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate, RegalocalWeb.Plugs.Acceptance])

    get("/", DashboardController, :show)
    get("/orders", OrderController, :index)
    get("/orders/search", OrderController, :search)
    get("/orders/:id", OrderController, :show)
    put("/orders/:id/payment_received", OrderController, :payment_received, as: :payment_received)
    put("/orders/:id/redeem", OrderController, :redeem, as: :order_redeemed)
    get("/business", BusinessController, :show)
    resources("/coupons", CouponController)
    put("/coupons/:id/publish", CouponController, :publish, as: :publish_coupon)
    put("/coupons/:id/unpublish", CouponController, :unpublish, as: :unpublish_coupon)
    put("/coupons/:id/archive", CouponController, :archive, as: :archive_coupon)
    put("/coupons/:id/activate", CouponController, :activate, as: :activate_coupon)
  end

  scope "/admin", RegalocalWeb.Admin, as: :admin do
    pipe_through([:browser, RegalocalWeb.Plugs.Veil.Authenticate])

    get("/business/edit", BusinessController, :edit)
    put("/business", BusinessController, :update)
  end

  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through [:browser]

      forward "/mailbox", Plug.Swoosh.MailboxPreview, base_path: "/dev/mailbox"
    end
  end
end

lib/regalocal_web/templates/page/about.html.eex
<%= container(:padded) do %>
  <h2 class="text-center text-3xl leading-9 font-extrabold text-primary-600 sm:text-4xl sm:leading-10 mb-6 border-b-2 border-gray-200 pb-6">
    <%= gettext("Sobre nosaltres") %>
  </h2>
  <h3 class="text-xl tracking-tight leading-10 font-bold text-gray-900 sm:text-xl sm:leading-none md:text-2xl mt-5">
    <%= gettext("Per què RegaLocal?") %>
  </h3>
  <p class="text-base leading-6 mt-2"><%= gettext("Degut a la crisi del COVID-19, una gran part del petit comerç s'ha vist amenaçat per la falta de gent al carrer. Molts d'aquests comerços han perdut tots o la majoria dels ingressos durant el confinament i estats d'alarma derivats de la situació.") %></p>
  <p class="text-base leading-6 mt-2"><%= gettext("D'altra banda, el confinament també afecta a la població general, que troba a faltar el contacte amb els seus amics i familiars.") %></p>
  <p class="text-base leading-6 mt-2"><%= gettext("Des de RegaLocal, volem donar solució a aquests dos reptes, efectivament canalitzant ingressos des d'aquells qui fan regals als comerços que necessiten subsistir, tot i prometent oferir els seus serveis després de la normalització de la situació.") %></p>
  <p class="text-base leading-6 mt-2"><%= gettext("A més, volem tenir un efecte a llarg termini en el teixit comercial, posant en contacte compradors amb propietaris del petit comerç, per establir relacions de confiança que aniran molt més enllà d'aquesta crisi.") %></p>
  <p class="text-base leading-6 mt-2"><%= gettext("És per això que és un servei gratuït i sense ànim de lucre, fet per aportar el nostre granet de sorra i revitalitzar l'economia local i de proximitat.") %></p>
  <h3 class="text-xl tracking-tight leading-10 font-bold text-gray-900 sm:text-xl sm:leading-none md:text-2xl mt-5">
    <%= gettext("Qui hi ha darrere?") %>
  </h3>
  <p class="text-base leading-6 mt-2"><%= gettext("El <a href=\"https://www.linkedin.com/in/txus/\">Txus</a>, el <a href=\"https://www.linkedin.com/in/josep-jaume-rey-peroy-a9701622/\">Josep</a> i l'<a href=\"https://www.linkedin.com/in/oriolgual/\">Oriol</a>, fundadors de <a href=\"https://codegram.com\">Codegram</a>, una agència internacional de productes digitals nascuda a Terrassa al 2009.") %></p>
  <h3 class="text-xl tracking-tight leading-10 font-bold text-gray-900 sm:text-xl sm:leading-none md:text-2xl mt-5">
    <%= gettext("Com va néixer?") %>
  </h3>
  <p class="text-base leading-6 mt-2"><%= gettext("RegaLocal neix de la nostra participació en el <a href=\"https://hackovid.cat/\">Hackovid</a>, una hackathon del 6 al 12 d'Abril del 2020 amb l'objectiu de donar solucions a les necessitats més urgents identificades per la ciutadania en el context de la crisi del COVID-19.") %></p>
<% end %>

lib/regalocal_web/templates/page/cookies.html.eex
<%= container(:padded) do %>
  <h2 class="text-center text-3xl leading-9 font-extrabold text-primary-600 sm:text-4xl sm:leading-10 mb-6 border-b-2 border-gray-200 pb-6">
    <%= gettext("Política de Cookies") %>
  </h2>
  <p class="mt-2 text-base leading-6 "><%= gettext("El titular d'aquesta pàgina web l'informa que a través de les cookies que fem servir no reculls ni recull dades personals dels seus Usuaris. La finalitat de les cookies és oferir-li una excel·lent experiència de navegació i millorar els nostres serveis en funció dels usos que li doni als continguts publicats o els accessos que faci als diferents apartats de la mateixa.") %></p>
  <h3 class="text-xl tracking-tight leading-10 font-bold sm:text-3xl sm:leading-none md:text-2xl mt-5">
    <%= gettext("1. INFORMACIÓ GENERAL") %>
  </h3>
  <ol>
    <li>
      <h4 class="text-l tracking-tight leading-10 font-bold sm:text-xl sm:leading-none md:text-xl mt-4">
        <%= gettext("El que ha de saber sobres les Galetes") %>
      </h4>
      <p class="mt-2 text-base leading-6 "><%= gettext("Les galetes (galetes) són petits arxius que guarden informació en els dispositius mòbils dels Usuaris que fan servir la nostra plataforma o el nostre bloc.") %></p>
      <p class="mt-2 text-base leading-6 "><%= gettext("Les cookies s'associen amb el navegador d'un ordinador o dispositiu determinat. Gràcies a elles, resulta possible que Codegram reconegui els navegadors dels Usuaris després que aquests hagin visitat la web per primera vegada, determinant així les seves preferències de navegació i, a partir d'això, avaluar-les, podent utilitzar-les com a indicadors per millorar el nostre contingut i navegació a la Web.") %></p>
    </li>
    <li>
      <h4 class="text-l tracking-tight leading-10 font-bold sm:text-xl sm:leading-none md:text-xl mt-4">
        <%= gettext("Les cookies que utilitza Codegram") %>
      </h4>
      <p class="mt-2 text-base leading-6 "><%= gettext("En el quadre que apareix a continuació s'inclouen els detalls, finalitat, el tipus i les classes de galetes que hem implementat en la nostra plataforma i el nostre bloc. Per a la seva comprensió, cal que conegui la definició de les cookies pròpies i de tercers:") %></p>
      <p class="mt-2 text-base leading-6 "><%= gettext("Galetes de tercers: són gestionades per altres empreses i instal·lades des dels seus equips i / o dominis a l'equip terminal de l'Usuari.") %></p>
      <p class="mt-2 text-base leading-6 "><%= gettext("Galetes Propies:són gestionades per la nostra empresa i instal·lades des dels nostres ordinadors a l'equip terminal de l'Usuari.") %></p>
    </li>
  </ol>
  <h3 class="text-xl tracking-tight leading-10 font-bold sm:text-3xl sm:leading-none md:text-2xl mt-5">
    <%= gettext("2. COOKIES UTILITZADES") %>
  </h3>
  <h4 class="text-l tracking-tight leading-10 font-bold sm:text-xl sm:leading-none md:text-xl mt-4">
    <%= gettext("2.1. Tipus de galetes de la pàgina web") %>
  </h4>
  <ul>
    <li>
      <dl class="border-t-2 mt-2">
        <div>
          <div>
            <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Cookie ID") %></dt>
            <dd class="mt-2">_regalocal_key</dd>
            <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Finalitat") %></dt>
            <dd class="mt-2"><%= gettext("Emmagatzema informació de l'usuari i de les seves sessions per millor la seva experiència.") %></dd>
            <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Data de Caducitat") %></dt>
            <dd class="mt-2"><%= gettext("Sessió") %></dd>
            <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Pròpia o de Tercers") %></dt>
            <dd class="mt-2"><%= gettext("Pròpia") %></dd>
            <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Responsable") %></dt>
            <dd class="mt-2"><%= gettext("Regalocal") %></dd>
          </div>
        </div>
      </dl>
    </li>
    <li>
      <dl class="mt-2 border-t-2">
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Cookie ID") %></dt>
        <dd class="mt-2"><%= gettext("_session_unique_id") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Finalitat") %></dt>
        <dd class="mt-2"><%= gettext("Emmagatzema informació per identificar l'usuari") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Data de Caducitat") %></dt>
        <dd class="mt-2"><%= gettext("Sessió") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Pròpia o de Tercers") %></dt>
        <dd class="mt-2"><%= gettext("Pròpia") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Responsable") %></dt>
        <dd class="mt-2"><%= gettext("Regalocal") %></dd>
      </dl>
    </li>
    <li>
      <dl class="mt-2 border-t-2">
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Cookie ID") %></dt>
        <dd class="mt-2"><%= gettext("_cfduid") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Finalitat") %></dt>
        <dd class="mt-2"><%= gettext("Usada per identificar un individu darrere d'una IP comú i establir mesures de seguretat") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Data de Caducitat") %></dt>
        <dd class="mt-2"><%= gettext("3 mesos") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Pròpia o de Tercers") %></dt>
        <dd class="mt-2"><%= gettext("Tercers") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Responsable") %></dt>
        <dd class="mt-2"><%= gettext("Cloudflare") %></dd>
      </dl>
    </li>
    <li>
      <dl class="mt-2 border-t-2">
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Cookie ID") %></dt>
        <dd class="mt-2"><%= gettext("crisp-client / session") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Finalitat") %></dt>
        <dd class="mt-2"><%= gettext("Usada per tenir una experiència consistent en el xat de suport.") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Data de Caducitat") %></dt>
        <dd class="mt-2"><%= gettext("6 mesos") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Pròpia o de Tercers") %></dt>
        <dd class="mt-2"><%= gettext("Tercers") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Responsable") %></dt>
        <dd class="mt-2"><%= gettext("Crisp") %></dd>
      </dl>
    </li>
    <li>
      <dl class="mt-2 border-t-2">
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Cookie ID") %></dt>
        <dd class="mt-2"><%= gettext("crisp-client / domain-detect") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Finalitat") %></dt>
        <dd class="mt-2"><%= gettext("Usada per desactivar funcions al xat quan hi ha massa usuaris a el mateix temps.") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Data de Caducitat") %></dt>
        <dd class="mt-2"><%= gettext("6 mesos") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Pròpia o de Tercers") %></dt>
        <dd class="mt-2"><%= gettext("Tercers") %></dd>
        <dt class="mt-2 text-lg leading-6 font-medium text-gray-900"><%= gettext("Responsable") %></dt>
        <dd class="mt-2"><%= gettext("Crisp") %></dd>
      </dl>
    </li>
    <h4 class="text-l tracking-tight leading-10 font-bold sm:text-xl sm:leading-none md:text-xl mt-4">
      <%= gettext("2.2. Notes sobre l'ús de galetes i altres tècniques de spamming") %>
    </h4>
    <p class="mt-2 text-base leading-6 "><%= gettext("Com Usuari queda informat de la presència de cookies en aquesta plataforma per tal de facilitar l'ús i navegació per la mateixa. Ara bé, té la possibilitat de configurar el seu navegador per ser avisat en pantalla de la recepció de cookies i per impedir la instal·lació de les mateixes en el seu disc dur.") %></p>
    <p class="mt-2 text-base leading-6 "><%= gettext("Si té dubtes, en el punt 4 d'aquest document té més informació. També pot consultar les instruccions i manuals del seu navegador per ampliar aquesta informació.") %></p>
    <p class="mt-2 text-base leading-6 "><%= gettext("Per utilitzar o navegar per la nostra pàgina web o utilitzar la plataforma no resulta necessari que permeti la instal·lació de cookies, sense perjudici que per això succeeixi que no pugui accedir a alguns dels serveis o apartats de la web.") %></p>
    <p class="mt-2 text-base leading-6 "><%= gettext("Informar-també que Codegram no utilitza tècniques de \"spamming\"i que únicament tractarà les dades que l'Usuari transmeti mitjançant l'ús dels formularis electrònics de contacte, missatges de correu electrònic o continguts facilitats a través dels serveis de la pàgina web, per a les finalitats expressades en el nostre Avís legal i en la nostra Política de Privacitat.") %></p>
    <h3 class="text-xl tracking-tight leading-10 font-bold sm:text-3xl sm:leading-none md:text-2xl mt-5">
      <%= gettext("3. L'ACCEPTACIÓ DE LES COOKIES EN LA NOSTRA PLATAFORMA") %>
    </h3>
    <p class="mt-2 text-base leading-6 "><%= gettext("La Llei 34/2002, de 11 de juliol, de Serveis de la Societat de la Informació i de Comerç Electrònic (en endavant, LSSICE), en relació amb les galetes, exigeix que els Usuaris siguin informats amb caràcter previ a l'experiència de navegació a la plataforma sobre l'ús, tipus i finalitat de les cookies. Aquesta és la raó per la qual hem implementat un avís informatiu que es desplega un cop accedeix a la nostra plataforma, informant-li de manera prèvia i expressa, complint amb el precepte legal.") %></p>
    <p class="mt-2 text-base leading-6 "><%= gettext("És important que tingui en compte que en aquest avís trobarà dues opcions: la primera, que li permetrà accedir a aquest text informatiu, i la segona, que podrà usar per acceptar la instal·lació de les cookies al seu equip terminal.") %></p>
    <p class="mt-2 text-base leading-6 "><%= gettext("Com a d'Usuari, si omet l'acceptació de l'ús de les cookies i continua navegant a la nostra plataforma, entendrem que hi ha un consentiment tàcit per la seva part per poder aplicar i utilitzar les galetes descrites en l'apartat anterior i, amb això, donarem compliment a que exigeix la LSSICE.") %></p>
    <h3 class="text-xl tracking-tight leading-10 font-bold sm:text-3xl sm:leading-none md:text-2xl mt-5">
      <%= gettext("4. COM POT DESINSTAL·LAR les COOKIES DES DE LA SEVA NAVEGADOR?") %>
    </h3>
    <p class="mt-2 text-base leading-6 "><%= gettext("Si voleu desinstal·lar les galetes des del seu navegador li indiquem alguns enllaços que podrà consultar en funció de l'tipus de navegador que tingui instal·lat al seu equip terminal.") %></p>
    <ul>
      <li><%= gettext("A Google Chrome: https://support.google.com/chrome/answer/95647?hl=es") %></li>
      <li><%= gettext("A Safari: https://support.apple.com/kb/ph5042") %></li>
      <li><%= gettext("En Mozilla Firefox: https: //support.mozilla .org / a-US / kb / disable-third-party-galetes") %></li>
      <li><%= gettext("a Internet Explorer: http://windows.microsoft.com/en-US/windows-vista/block-or-allow-cookies") %></li>
      <li><%= gettext("en Opera: http: //www.opera.com/help/tutorials/security/privacy/") %></li>
    </ul>
    <p class="mt-2 text-base leading-6 "><%= gettext("Us advertim que, després de realitzar el procés de desinstal de cookies des del seu navegador, això pot dificultar o impedir l'accés o navegació a determinades parts de la nostra pàgina web.") %></p>
    <h3 class="text-xl tracking-tight leading-10 font-bold sm:text-3xl sm:leading-none md:text-2xl mt-5">
      <%= gettext("5. SOBRE LES COOKIES DE LES XARXES SOCIALS") %>
    </h3>
    <p class="mt-2 text-base leading-6 "><%= gettext("Finalment, volem advertir-li que la nostra plataforma no administra les xarxes socials o plataforma de tercers com Facebook o Twitter, on Codegram té presència, amb la qual cosa tampoc és responsable de les galetes que instal·len aquestes plataformes.") %></p>
    <p class="mt-2 text-base leading-6 "><%= gettext("Com a d'Usuari de la nostra plataforma en línia, està obligat a consultar les polítiques de privacitat i galetes d'aquestes xarxes per estar a l'corrent de l'tipus i finalitats i decidir acceptar-les o rebutjar-les.") %></p>
    <ul>
      <li><%= gettext("Galetes utilitzades per Facebook: https://www.facebook.com/help/cookies/") %></li>
      <li><%= gettext("Galetes utilitzades per Twitter: https://help.twitter.com/es/rules-and-policies/twitter-cookies") %></li>
      <li><%= gettext("Galetes utilitzades per YouTube: https://policies.google.com/technologies/cookies?hl=es&gl=es") %></li>
    </ul>
  <% end %>

lib/regalocal_web/templates/page/index.html.eex
<div class="relative overflow-hidden">
  <div class="relative pb-12 sm:pb-16 md:pb-20 lg:pb-28 xl:pb-32">
    <div class="mt-6 mx-auto max-w-screen-xl px-6 sm:mt-8 sm:px-8 md:mt-12 lg:mt-16 xl:mt-20">
      <div class="text-center">
        <h2 class="text-4xl tracking-tight leading-10 font-extrabold text-gray-900 sm:text-5xl sm:leading-none md:text-6xl">
          <%= gettext("Regala <span class=\"text-primary-600\">solidaritat</span>") %>
          <br />
          <%= gettext("i ajuda el <span class=\"text-primary-600\">comerç local</span>") %>
        </h2>
        <p class="mt-3 max-w-md mx-auto text-base text-gray-500 sm:text-lg md:mt-5 md:text-xl md:max-w-3xl">
        <%= gettext("Ajuda als comerços i petits negocis a fer front a la crisi causada pel 🦠 COVID-19 i al mateix temps regala solidaritat als qui t'estimes.") %>
        </p>
        <div class="my-12 sm:mb-16 text-left max-w-5xl mx-auto">
          <ul class="md:grid md:grid-cols-3 md:col-gap-8 md:row-gap-10">
            <li>
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="flex items-center justify-center h-12 w-12 rounded-md bg-secondary-500 text-white">
                    <svg fill="currentColor" viewBox="0 0 20 20" class="w-8 h-8"><path fill-rule="evenodd" d="M5 2a1 1 0 011 1v1h1a1 1 0 010 2H6v1a1 1 0 01-2 0V6H3a1 1 0 010-2h1V3a1 1 0 011-1zm0 10a1 1 0 011 1v1h1a1 1 0 110 2H6v1a1 1 0 11-2 0v-1H3a1 1 0 110-2h1v-1a1 1 0 011-1zM12 2a1 1 0 01.967.744L14.146 7.2 17.5 9.134a1 1 0 010 1.732l-3.354 1.935-1.18 4.455a1 1 0 01-1.933 0L9.854 12.8 6.5 10.866a1 1 0 010-1.732l3.354-1.935 1.18-4.455A1 1 0 0112 2z" clip-rule="evenodd"></path></svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h5 class="text-lg leading-6 font-medium text-gray-900"><%= gettext("Regala solidaritat") %></h5>
                  <p class="mt-2 text-base leading-6 text-gray-500">
                  <%= gettext("Regala cupons als teus per a gaudir d'activitats després del confinament.") %>
                  </p>
                </div>
              </div>
            </li>
            <li class="mt-10 md:mt-0">
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="flex items-center justify-center h-12 w-12 rounded-md bg-secondary-500 text-white">
                    <svg fill="currentColor" viewBox="0 0 20 20" class="w-8 h-8"><path fill-rule="evenodd" d="M4 4a2 2 0 00-2 2v4a2 2 0 002 2V6h10a2 2 0 00-2-2H4zm2 6a2 2 0 012-2h8a2 2 0 012 2v4a2 2 0 01-2 2H8a2 2 0 01-2-2v-4zm6 4a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd"></path></svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h5 class="text-lg leading-6 font-medium text-gray-900"><%= gettext("Ajuda el comerç local") %></h5>
                  <p class="mt-2 text-base leading-6 text-gray-500">
                  <%= gettext("El teu pagament ajuda a subsistir als comerços fins que recuperin la seva activitat.") %>
                  </p>
                </div>
              </div>
            </li>
            <li class="mt-10 md:mt-0">
              <div class="flex">
                <div class="flex-shrink-0">
                  <div class="flex items-center justify-center h-12 w-12 rounded-md bg-secondary-500 text-white">
                    <svg fill="currentColor" viewBox="0 0 20 20" class="w-8 h-8"><path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd"></path></svg>
                  </div>
                </div>
                <div class="ml-4">
                  <h5 class="text-lg leading-6 font-medium text-gray-900"><%= gettext("Quan el comerç reobri, gaudeix!") %></h5>
                  <p class="mt-2 text-base leading-6 text-gray-500">
                  <%= gettext("Quan el comerç reobri portes, gaudeix de temps amb els teus fent servir els cupons que vas regalar.") %>
                  </p>
                </div>
              </div>
            </li>
          </ul>
        </div>
        <form method="get" action="<%= Routes.search_path(@conn, :index) %>"  x-ref="form" x-data="{ status: 'initial', latitude: null, longitude: null }" class="mt-5 mx-auto flex justify-center md:mt-8">
          <input type="hidden" x-bind:value="latitude" name="latitude" />
          <input type="hidden" x-bind:value="longitude" name="longitude" />
          <button type="submit" @click.prevent="status = 'geolocating'; window.geolocate().then(coordinates => { latitude = coordinates.latitude; longitude = coordinates.longitude; $nextTick(() => setTimeout(() => $refs.form.submit(), 1)); status = 'searching'; }).catch(() => { status = 'errored' })" class="w-5/6 sm:w-2/3 md:w-1/2 lg:w-1/3 sm:mt-0 flex-shrink-0 mt-3 button" x-bind:disabled="status != 'initial'">
            <svg x-show="status !== 'errored'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" style="width: 1.2rem; height: 1.2rem; fill: currentColor;"><path d="M10 20S3 10.87 3 7a7 7 0 1 1 14 0c0 3.87-7 13-7 13zm0-11a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/></svg>
            <svg x-show="status === 'errored'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" style="width: 1.2rem; height: 1.2rem; fill: currentColor;"><path d="M0 10a10 10 0 1 1 20 0 10 10 0 0 1-20 0zm16.32-4.9L5.09 16.31A8 8 0 0 0 16.32 5.09zm-1.41-1.42A8 8 0 0 0 3.68 14.91L14.91 3.68z"/></svg>
            &nbsp;
            <span x-show="status === 'initial'"><%= gettext("Cerca comerços al teu voltant") %></span>
            <span x-show="status === 'geolocating'"><%= gettext("Esperant ubicació...") %></span>
            <span x-show="status === 'searching'"><%= gettext("Buscant comerços...") %></span>
            <span x-show="status === 'errored'"><%= gettext("Ubicació no disponible") %></span>
          </button>
        </form>
        <div class="mt-3 max-w-xxl mx-auto sm:flex sm:justify-center">
          <div class="mt-3 sm:mt-0 sm:ml-3 sm:flex-shrink-0">
            <%= link to: Routes.veil_business_path(@conn, :new), class: "w-full flex items-center justify-center px-5 py-3" do %>
              <svg xmlns="http://www.w3.org/2000/svg" style="fill: currentColor" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M17 11a1 1 0 0 1 0 2h-4v4a1 1 0 0 1-2 0v-4H7a1 1 0 0 1 0-2h4V7a1 1 0 0 1 2 0v4h4z"/></svg>
              <%= gettext("Afegir el meu comerç") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>